import { RouteObject } from "react-router-dom";

// nginx cannot know which paths the SPA owns, so it either falls everything
// back to index.html (and a dead URL returns 200 with an empty page) or it
// needs the list. The list is generated from the router so the two cannot
// drift: anything not in it is a real 404.

const SAFE_SEGMENT = /^[A-Za-z0-9_-]+$/;

/** "profile/:userId" -> "profile"; "" (index), "*" and ":id" -> null. */
function firstSegment(path: string | undefined): string | null {
  if (!path) return null;
  const segment = path.replace(/^\//, "").split("/")[0];
  if (!segment || segment === "*" || segment.charAt(0) === ":") return null;
  return segment;
}

/**
 * The nginx `location` block that lets known app routes fall back to the SPA
 * shell. Written to build/nginx.routes.conf by scripts/prerender.js and
 * included by deploy/nginx.snippet.conf.
 */
export function buildNginxRoutesConf(routes: RouteObject[]): string {
  const segments: string[] = [];
  for (const root of routes) {
    for (const child of root.children || []) {
      const segment = firstSegment(child.path);
      if (segment === null) continue;
      if (!SAFE_SEGMENT.test(segment)) {
        // Nothing here is escaped, so a segment with regex metacharacters would
        // silently widen or break the location match.
        throw new Error(`Route segment "${segment}" is not safe to inline into an nginx regex`);
      }
      if (segments.indexOf(segment) < 0) segments.push(segment);
    }
  }
  segments.sort();
  return [
    "# Generated by scripts/prerender.js from src/router/routes.tsx. Do not edit; regenerated on every build.",
    "# App routes: serve the prerendered page when one exists, otherwise the SPA shell",
    "# (build/app.html, the unfilled CRA template -- never index.html, which is the",
    "# prerendered homepage and would make React hydrate the wrong markup).",
    `location ~ ^/(${segments.join("|")})(/|$) {`,
    "  try_files $uri $uri/index.html /app.html;",
    "}",
    "",
  ].join("\n");
}
