// GENERATED FILE -- DO NOT EDIT BY HAND.
// Regenerate with: node scripts/generate-language-data.js
// Source: language_exchange_backend_application seeds/languages.js
//         and utils/languageCodes.js (the same catalog the API validates against).

/** Lowercased full catalog name -> flag. Preserves regional variants. */
export const CATALOG_NAME_TO_FLAG: Record<string, string> = {
  "english": "🇺🇸",
  "korean": "🇰🇷",
  "chinese (simplified)": "🇨🇳",
  "chinese (traditional)": "🇹🇼",
  "tagalog": "🇵🇭",
  "filipino": "🇵🇭",
  "arabic": "🇸🇦",
  "japanese": "🇯🇵",
  "vietnamese": "🇻🇳",
  "thai": "🇹🇭",
  "indonesian": "🇮🇩",
  "malay": "🇲🇾",
  "burmese": "🇲🇲",
  "khmer": "🇰🇭",
  "lao": "🇱🇦",
  "hindi": "🇮🇳",
  "bengali": "🇧🇩",
  "tamil": "🇮🇳",
  "telugu": "🇮🇳",
  "marathi": "🇮🇳",
  "urdu": "🇵🇰",
  "nepali": "🇳🇵",
  "sinhala": "🇱🇰",
  "spanish": "🇪🇸",
  "spanish (mexico)": "🇲🇽",
  "spanish (argentina)": "🇦🇷",
  "portuguese": "🇵🇹",
  "portuguese (brazil)": "🇧🇷",
  "portuguese (portugal)": "🇵🇹",
  "french": "🇫🇷",
  "french (canada)": "🇨🇦",
  "german": "🇩🇪",
  "italian": "🇮🇹",
  "russian": "🇷🇺",
  "ukrainian": "🇺🇦",
  "polish": "🇵🇱",
  "dutch": "🇳🇱",
  "swedish": "🇸🇪",
  "norwegian": "🇳🇴",
  "danish": "🇩🇰",
  "finnish": "🇫🇮",
  "greek": "🇬🇷",
  "czech": "🇨🇿",
  "romanian": "🇷🇴",
  "hungarian": "🇭🇺",
  "turkish": "🇹🇷",
  "english (us)": "🇺🇸",
  "english (uk)": "🇬🇧",
  "english (australia)": "🇦🇺",
  "english (canada)": "🇨🇦",
  "arabic (egyptian)": "🇪🇬",
  "arabic (levantine)": "🇱🇧",
  "arabic (gulf)": "🇸🇦",
  "arabic (moroccan darija)": "🇲🇦",
  "cantonese": "🇭🇰",
  "punjabi": "🇮🇳",
  "gujarati": "🇮🇳",
  "kannada": "🇮🇳",
  "malayalam": "🇮🇳",
  "odia": "🇮🇳",
  "assamese": "🇮🇳",
  "sindhi": "🇵🇰",
  "kashmiri": "🇮🇳",
  "dhivehi": "🇲🇻",
  "hebrew": "🇮🇱",
  "persian": "🇮🇷",
  "pashto": "🇦🇫",
  "dari": "🇦🇫",
  "kurdish": "🇮🇶",
  "swahili": "🇰🇪",
  "amharic": "🇪🇹",
  "tigrinya": "🇪🇷",
  "oromo": "🇪🇹",
  "somali": "🇸🇴",
  "afrikaans": "🇿🇦",
  "zulu": "🇿🇦",
  "xhosa": "🇿🇦",
  "sesotho": "🇱🇸",
  "setswana": "🇧🇼",
  "shona": "🇿🇼",
  "kinyarwanda": "🇷🇼",
  "luganda": "🇺🇬",
  "chichewa": "🇲🇼",
  "malagasy": "🇲🇬",
  "yoruba": "🇳🇬",
  "igbo": "🇳🇬",
  "hausa": "🇳🇬",
  "wolof": "🇸🇳",
  "fula": "🇸🇳",
  "uzbek": "🇺🇿",
  "kazakh": "🇰🇿",
  "kyrgyz": "🇰🇬",
  "tajik": "🇹🇯",
  "turkmen": "🇹🇲",
  "mongolian": "🇲🇳",
  "georgian": "🇬🇪",
  "armenian": "🇦🇲",
  "azerbaijani": "🇦🇿",
  "bulgarian": "🇧🇬",
  "serbian": "🇷🇸",
  "croatian": "🇭🇷",
  "slovak": "🇸🇰",
  "slovenian": "🇸🇮",
  "bosnian": "🇧🇦",
  "macedonian": "🇲🇰",
  "belarusian": "🇧🇾",
  "estonian": "🇪🇪",
  "latvian": "🇱🇻",
  "lithuanian": "🇱🇹",
  "catalan": "🇪🇸",
  "galician": "🇪🇸",
  "basque": "🇪🇸",
  "occitan": "🇫🇷",
  "icelandic": "🇮🇸",
  "luxembourgish": "🇱🇺",
  "frisian": "🇳🇱",
  "faroese": "🇫🇴",
  "irish": "🇮🇪",
  "welsh": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "scottish gaelic": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "breton": "🇫🇷",
  "maltese": "🇲🇹",
  "albanian": "🇦🇱",
  "maori": "🇳🇿",
  "samoan": "🇼🇸",
  "tongan": "🇹🇴",
  "fijian": "🇫🇯",
  "hawaiian": "🇺🇸",
  "haitian creole": "🇭🇹",
  "quechua": "🇵🇪",
  "guarani": "🇵🇾",
  "esperanto": "🌐",
  "latin": "🏛️",
  "american sign language": "🤟",
  "british sign language": "🤟",
  "japanese sign language": "🤟",
  "korean sign language": "🤟",
};

/** Lowercased language name -> base ISO 639-1 code. */
export const NAME_TO_ISO: Record<string, string> = {
  "english": "en",
  "korean": "ko",
  "japanese": "ja",
  "chinese": "zh",
  "spanish": "es",
  "french": "fr",
  "german": "de",
  "italian": "it",
  "portuguese": "pt",
  "russian": "ru",
  "arabic": "ar",
  "bengali": "bn",
  "czech": "cs",
  "danish": "da",
  "dutch": "nl",
  "finnish": "fi",
  "greek": "el",
  "hebrew": "he",
  "hindi": "hi",
  "hungarian": "hu",
  "indonesian": "id",
  "malay": "ms",
  "norwegian": "no",
  "persian": "fa",
  "polish": "pl",
  "romanian": "ro",
  "swedish": "sv",
  "tajik": "tg",
  "thai": "th",
  "turkish": "tr",
  "ukrainian": "uk",
  "urdu": "ur",
  "vietnamese": "vi",
  "chinese (simplified)": "zh",
  "chinese (traditional)": "zh",
  "english (us)": "en",
  "filipino": "tl",
  "portuguese (brazil)": "pt",
  "portuguese (portugal)": "pt",
  "english (uk)": "en",
  "english (australia)": "en",
  "english (canada)": "en",
  "cantonese": "zh",
  "spanish (mexico)": "es",
  "spanish (spain)": "es",
  "spanish (argentina)": "es",
  "french (canada)": "fr",
  "arabic (msa)": "ar",
  "arabic (egyptian)": "ar",
  "arabic (levantine)": "ar",
  "arabic (gulf)": "ar",
  "arabic (moroccan darija)": "ar",
  "tagalog": "tl",
  "burmese": "my",
  "khmer": "km",
  "lao": "lo",
  "tamil": "ta",
  "telugu": "te",
  "marathi": "mr",
  "nepali": "ne",
  "sinhala": "si",
  "punjabi": "pa",
  "gujarati": "gu",
  "kannada": "kn",
  "malayalam": "ml",
  "odia": "or",
  "assamese": "as",
  "sindhi": "sd",
  "kashmiri": "ks",
  "dhivehi": "dv",
  "pashto": "ps",
  "kurdish": "ku",
  "swahili": "sw",
  "amharic": "am",
  "tigrinya": "ti",
  "oromo": "om",
  "somali": "so",
  "afrikaans": "af",
  "zulu": "zu",
  "xhosa": "xh",
  "setswana": "tn",
  "sesotho": "st",
  "shona": "sn",
  "kinyarwanda": "rw",
  "luganda": "lg",
  "malagasy": "mg",
  "yoruba": "yo",
  "chichewa": "ny",
  "igbo": "ig",
  "hausa": "ha",
  "wolof": "wo",
  "fula": "ff",
  "kazakh": "kk",
  "kyrgyz": "ky",
  "uzbek": "uz",
  "turkmen": "tk",
  "mongolian": "mn",
  "georgian": "ka",
  "azerbaijani": "az",
  "bulgarian": "bg",
  "armenian": "hy",
  "serbian": "sr",
  "croatian": "hr",
  "slovak": "sk",
  "slovenian": "sl",
  "bosnian": "bs",
  "macedonian": "mk",
  "belarusian": "be",
  "estonian": "et",
  "lithuanian": "lt",
  "latvian": "lv",
  "catalan": "ca",
  "galician": "gl",
  "basque": "eu",
  "occitan": "oc",
  "icelandic": "is",
  "luxembourgish": "lb",
  "frisian": "fy",
  "faroese": "fo",
  "irish": "ga",
  "welsh": "cy",
  "scottish gaelic": "gd",
  "breton": "br",
  "maltese": "mt",
  "albanian": "sq",
  "maori": "mi",
  "samoan": "sm",
  "tongan": "to",
  "fijian": "fj",
  "haitian creole": "ht",
  "quechua": "qu",
  "guarani": "gn",
  "esperanto": "eo",
  "latin": "la",
};

/** Base ISO 639-1 code -> flag. */
export const CODE_TO_FLAG: Record<string, string> = {
  "en": "🇺🇸",
  "ko": "🇰🇷",
  "ja": "🇯🇵",
  "zh": "🇨🇳",
  "es": "🇪🇸",
  "fr": "🇫🇷",
  "de": "🇩🇪",
  "it": "🇮🇹",
  "pt": "🇵🇹",
  "ru": "🇷🇺",
  "ar": "🇸🇦",
  "bn": "🇧🇩",
  "cs": "🇨🇿",
  "da": "🇩🇰",
  "nl": "🇳🇱",
  "fi": "🇫🇮",
  "el": "🇬🇷",
  "he": "🇮🇱",
  "hi": "🇮🇳",
  "hu": "🇭🇺",
  "id": "🇮🇩",
  "ms": "🇲🇾",
  "no": "🇳🇴",
  "fa": "🇮🇷",
  "pl": "🇵🇱",
  "ro": "🇷🇴",
  "sv": "🇸🇪",
  "tg": "🇹🇯",
  "th": "🇹🇭",
  "tr": "🇹🇷",
  "uk": "🇺🇦",
  "ur": "🇵🇰",
  "vi": "🇻🇳",
  "tl": "🇵🇭",
  "my": "🇲🇲",
  "km": "🇰🇭",
  "lo": "🇱🇦",
  "ta": "🇮🇳",
  "te": "🇮🇳",
  "mr": "🇮🇳",
  "ne": "🇳🇵",
  "si": "🇱🇰",
  "pa": "🇮🇳",
  "gu": "🇮🇳",
  "kn": "🇮🇳",
  "ml": "🇮🇳",
  "or": "🇮🇳",
  "as": "🇮🇳",
  "sd": "🇵🇰",
  "ks": "🇮🇳",
  "dv": "🇲🇻",
  "ps": "🇦🇫",
  "ku": "🇮🇶",
  "sw": "🇰🇪",
  "am": "🇪🇹",
  "ti": "🇪🇷",
  "om": "🇪🇹",
  "so": "🇸🇴",
  "af": "🇿🇦",
  "zu": "🇿🇦",
  "xh": "🇿🇦",
  "tn": "🇧🇼",
  "st": "🇱🇸",
  "sn": "🇿🇼",
  "rw": "🇷🇼",
  "lg": "🇺🇬",
  "mg": "🇲🇬",
  "yo": "🇳🇬",
  "ny": "🇲🇼",
  "ig": "🇳🇬",
  "ha": "🇳🇬",
  "wo": "🇸🇳",
  "ff": "🇸🇳",
  "kk": "🇰🇿",
  "ky": "🇰🇬",
  "uz": "🇺🇿",
  "tk": "🇹🇲",
  "mn": "🇲🇳",
  "ka": "🇬🇪",
  "az": "🇦🇿",
  "bg": "🇧🇬",
  "hy": "🇦🇲",
  "sr": "🇷🇸",
  "hr": "🇭🇷",
  "sk": "🇸🇰",
  "sl": "🇸🇮",
  "bs": "🇧🇦",
  "mk": "🇲🇰",
  "be": "🇧🇾",
  "et": "🇪🇪",
  "lt": "🇱🇹",
  "lv": "🇱🇻",
  "ca": "🇪🇸",
  "gl": "🇪🇸",
  "eu": "🇪🇸",
  "oc": "🇫🇷",
  "is": "🇮🇸",
  "lb": "🇱🇺",
  "fy": "🇳🇱",
  "fo": "🇫🇴",
  "ga": "🇮🇪",
  "cy": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "gd": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "br": "🇫🇷",
  "mt": "🇲🇹",
  "sq": "🇦🇱",
  "mi": "🇳🇿",
  "sm": "🇼🇸",
  "to": "🇹🇴",
  "fj": "🇫🇯",
  "ht": "🇭🇹",
  "qu": "🇵🇪",
  "gn": "🇵🇾",
  "eo": "🌐",
  "la": "🏛️",
};
